package com.example.sumayerestaurant.ui.delivery;

import android.app.AlertDialog; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity;
import com.example.sumayerestaurant.data.api.RetrofitClient; import com.example.sumayerestaurant.data.local.TokenManager; import com.example.sumayerestaurant.data.model.*; import java.util.*; import retrofit2.*;

/** Delivery dashboard: cards refresh from the server and expose only the next valid action. */
public class DeliveryActivity extends AppCompatActivity {
 private Long branch; private LinearLayout cards; private EditText order,customer,address,fee;
 @Override public void onCreate(Bundle b){super.onCreate(b);User u=new TokenManager(this).getUser();branch=(u==null||u.getBranchId()==null)?1L:u.getBranchId();setTitle("Oda za Delivery");LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);Button refresh=new Button(this);refresh.setText("Sasisha oda za delivery");root.addView(refresh);cards=new LinearLayout(this);cards.setOrientation(LinearLayout.VERTICAL);root.addView(cards);order=f("ID ya oda ya delivery");customer=f("ID ya mteja");address=f("Anwani ya kufikisha");fee=f("Ada ya delivery (TZS, si lazima)");root.addView(order);root.addView(customer);root.addView(address);root.addView(fee);Button create=new Button(this);create.setText("Thibitisha delivery");root.addView(create);setContentView(root);refresh.setOnClickListener(v->load());create.setOnClickListener(v->create());load();}
 private EditText f(String hint){EditText x=new EditText(this);x.setHint(hint);x.setMinHeight(84);return x;}
 private void load(){if(branch==null){toast("Tawi halijapatikana.");return;}RetrofitClient.getApiService(this).getDeliveries(branch).enqueue(new Callback<List<DeliveryOrder>>(){public void onResponse(Call<List<DeliveryOrder>>c,Response<List<DeliveryOrder>>r){cards.removeAllViews();if(!r.isSuccessful()||r.body()==null){note("Imeshindikana kupakia delivery.");return;}if(r.body().isEmpty()){note("Hakuna delivery za sasa.");return;}for(DeliveryOrder d:r.body())addCard(d);}public void onFailure(Call<List<DeliveryOrder>>c,Throwable t){note("Hakuna mtandao. Tafadhali jaribu tena.");}});}
 private void addCard(DeliveryOrder d){LinearLayout card=new LinearLayout(this);card.setPadding(12,18,12,18);card.setOrientation(LinearLayout.VERTICAL);TextView text=new TextView(this);String no=d.getOrder()==null?"Oda":d.getOrder().getOrderNumber();String who=d.getCustomer()==null?"Mteja":d.getCustomer().toString();text.setText(no+"\n"+who+"\n"+d.getDeliveryAddress()+"\nHali: "+d.getStatus()+" • Ada: TZS "+d.getDeliveryFee());text.setTextSize(16);card.addView(text);String action=action(d.getStatus());if(action!=null){Button next=new Button(this);next.setText(action);next.setOnClickListener(v->confirmStatus(d,action));card.addView(next);}if(d.getRider()==null&&action!=null){Button assign=new Button(this);assign.setText("Mpe mtoa huduma");assign.setOnClickListener(v->assign(d));card.addView(assign);}cards.addView(card);}
 private String action(String s){if("PENDING".equals(s))return "Thibitisha";if("CONFIRMED".equals(s))return "Anza kutayarisha";if("PREPARING".equals(s))return "Tayari";if("READY".equals(s))return "Tuma";if("OUT_FOR_DELIVERY".equals(s))return "Imewasilishwa";return null;}
 private String status(String a){if("Thibitisha".equals(a))return "CONFIRMED";if("Anza kutayarisha".equals(a))return "PREPARING";if("Tayari".equals(a))return "READY";if("Tuma".equals(a))return "OUT_FOR_DELIVERY";return "DELIVERED";}
 private void confirmStatus(DeliveryOrder d,String a){new AlertDialog.Builder(this).setMessage("Una uhakika unataka "+a.toLowerCase()+" delivery hii?").setNegativeButton("Ghairi",null).setPositiveButton("Endelea",(x,w)->RetrofitClient.getApiService(this).updateDeliveryStatus(branch,d.getId(),status(a)).enqueue(saved("Hali ya delivery imesasishwa."))).show();}
 private void assign(DeliveryOrder d){EditText rider=f("ID ya mtoa huduma");new AlertDialog.Builder(this).setTitle("Mpe mtoa huduma").setView(rider).setNegativeButton("Ghairi",null).setPositiveButton("Thibitisha",(x,w)->{try{Map<String,Object> body=new HashMap<>();body.put("riderId",Long.parseLong(rider.getText().toString()));RetrofitClient.getApiService(this).assignDelivery(branch,d.getId(),body).enqueue(saved("Mtoa huduma amepewa oda."));}catch(Exception e){toast("Weka ID sahihi ya mtoa huduma.");}}).show();}
 private void create(){try{if(address.getText().toString().trim().isEmpty())throw new Exception();Map<String,Object> body=new HashMap<>();body.put("orderId",Long.parseLong(order.getText().toString()));body.put("customerId",Long.parseLong(customer.getText().toString()));body.put("deliveryAddress",address.getText().toString().trim());if(!fee.getText().toString().trim().isEmpty())body.put("deliveryFee",fee.getText().toString().trim());RetrofitClient.getApiService(this).createDelivery(branch,body).enqueue(saved("Delivery imehifadhiwa."));}catch(Exception e){toast("Jaza oda, mteja na anwani sahihi.");}}
 private Callback<Object> saved(String ok){return new Callback<Object>(){public void onResponse(Call<Object>c,Response<Object>r){if(r.isSuccessful()){toast(ok);load();}else toast("Imeshindikana kuhifadhi mabadiliko.");}public void onFailure(Call<Object>c,Throwable t){toast("Hakuna mtandao. Tafadhali jaribu tena.");}};}private void note(String s){TextView t=new TextView(this);t.setText(s);cards.addView(t);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
